# Generated by Django 3.1.5 on 2021-01-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='blacklist',
            field=models.BooleanField(default=False),
        ),
    ]
