# Generated by Django 3.1.5 on 2021-01-28 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_blacklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='blacklist',
        ),
    ]
