# Generated by Django 3.1.5 on 2021-01-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210128_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bl',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_bl_+', to='chat.UserProfile'),
        ),
    ]
