# Generated by Django 3.1.5 on 2021-01-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210128_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bl',
            field=models.ManyToManyField(blank=True, related_name='blacklist', to='chat.UserProfile'),
        ),
    ]
