# Generated by Django 3.1.5 on 2021-01-28 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
