# Generated by Django 3.1.5 on 2021-01-28 22:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0009_auto_20210129_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bl',
            field=models.ManyToManyField(blank=True, related_name='blacklist', to=settings.AUTH_USER_MODEL),
        ),
    ]
